# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Customer Id')),
                ('cust_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Customer Name')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer email')),
                ('mobile', models.IntegerField(blank=True, null=True, verbose_name='Mobile Number')),
                ('wallet_amount', models.IntegerField(blank=True, null=True, verbose_name='Wallet Amount')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
