# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('item_id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Item ID')),
                ('item_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Station Name')),
                ('cost_per_plate', models.IntegerField(blank=True, null=True, verbose_name='Cost per Plate')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
