# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pnr',
            fields=[
                ('pnr_no', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Pnr No')),
                ('coach_no', models.IntegerField(blank=True, null=True, verbose_name='Coach Number')),
                ('berth_no', models.IntegerField(blank=True, null=True, verbose_name='Berth Number')),
                ('train_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='PNR Created at')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
