# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('item_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Item ID')),
                ('item_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Station Name')),
                ('cost_per_plate', models.IntegerField(blank=True, null=True, verbose_name='Cost per Plate')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fooditem',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.CharField(db_column='shop_id', max_length=7, primary_key=True, serialize=False, verbose_name='Shop ID')),
                ('shop_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Shop Name')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rating')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
                ('station', models.ForeignKey(blank=True, db_column='station_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='station.Station')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='shop',
            field=models.ForeignKey(blank=True, db_column='shop_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
    ]
