# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='numratings',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Ratings'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Rating'),
        ),
    ]
