# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pnr',
            fields=[
                ('pnr_no', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name=b'Pnr No')),
                ('coach_no', models.IntegerField(blank=True, null=True, verbose_name=b'Coach Number')),
                ('berth_no', models.IntegerField(blank=True, null=True, verbose_name=b'Berth Number')),
                ('train_start_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Start Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'PNR Created at')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pnr',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arr_time', models.TimeField(blank=True, null=True, verbose_name=b'Arrival Time')),
                ('dept_time', models.TimeField(blank=True, null=True, verbose_name=b'Departure Time')),
                ('stop_num', models.IntegerField(blank=True, null=True, verbose_name=b'Stop Number')),
                ('day_of_journey', models.IntegerField(blank=True, null=True, verbose_name=b'Day of Journey')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station.Station')),
            ],
            options={
                'db_table': 'stop',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name=b'Train No')),
                ('train_name', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Train Name')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name=b'Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name=b'End Time')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
                ('from_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_station_train', to='station.Station')),
                ('to_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_station_train', to='station.Station')),
            ],
            options={
                'db_table': 'train',
            },
        ),
        migrations.AddField(
            model_name='stop',
            name='train_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='train.Train'),
        ),
        migrations.AddField(
            model_name='pnr',
            name='train_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='train.Train'),
        ),
    ]
