# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-29 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('train_no', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name=b'Train No.')),
            ],
        ),
    ]
