# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20161029_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name=b'End Time'),
        ),
        migrations.AlterField(
            model_name='train',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name=b'Start Time'),
        ),
        migrations.AlterField(
            model_name='train',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
