# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Station ID')),
                ('station_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Station Name')),
                ('no_of_platforms', models.IntegerField(blank=True, null=True, verbose_name='No of Platforms')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
    ]
