# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Station ID')),
                ('station_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Station Name')),
                ('no_of_platforms', models.IntegerField(blank=True, null=True, verbose_name='No of Platforms')),
                ('time_stamp', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
