# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
