# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pnr', '0001_initial'),
        ('customer', '0001_initial'),
        ('fooditem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Received'), ('2', 'Prepared'), ('3', 'Dispatched'), ('4', 'Delivered'), ('8', 'Cancelled'), ('9', 'Not-Recieved')], max_length=1, null=True, verbose_name='Status of Order')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
                ('cust_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fooditem.Fooditem')),
                ('pnr_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pnr.Pnr')),
            ],
        ),
    ]
