# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arr_time', models.TimeField(blank=True, null=True, verbose_name='Arrival Time')),
                ('dept_time', models.TimeField(blank=True, null=True, verbose_name='Departure Time')),
                ('stop_num', models.IntegerField(blank=True, null=True, verbose_name='Stop Number')),
                ('day_of_journey', models.IntegerField(blank=True, null=True, verbose_name='Day of Journey')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
                ('station_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station.Station')),
                ('train_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='train.Train')),
            ],
        ),
    ]
